CC = g++

all:
	$(CC) strshuffle.cpp -o strshuffle
	$(CC) strio.cpp -o strio
	$(CC) rand.cpp -o rand

shuffle:
	$(CC) strshuffle.cpp -o strshuffle

io:
	$(CC) strio.cpp -o strio

rand:
	$(CC) rand.cpp -o rand

clean:
	rm -f strshuffle
	rm -f strio
	rm -f rand
